### PR TITLE
Added missing Market properties

### PR DESCRIPTION
**Pull request by jfversluis**
A few properties were added to the Bittrex response, although not documented

### CODE REVIEW

**Review by Domysee — APPROVED** [review]
Thank you for adding that!

**Comment by jfversluis** [comment]
No problem! Are you planning on releasing a new NuGet version with this soon by any chance? 🙂

**Comment by Domysee** [comment]
Done ;)

**Comment by jfversluis** [comment]
Awesome dude! Thanks!

**Pull request merged**
